### ISSUE TITLE
vscode 插件报错 (使用快捷键：Alt+Shift+T）

### ISSUE THREAD

**Issue by AnglusWang** [liulongbin1314/escook-translate#1]
escook-translate:ERROR_1 翻译失败，请稍后再试~ Something went wrong! The response is {"statusCode":205,"errorMessage":""}.

**Comment by longan2244** [comment]
你好彬哥 翻译出现以下问题 ，希望可以修复一下谢谢 escook-translate:ERROR_1 翻译失败，请稍后再试~ Something went wrong! The response is {"statusCode":205,"errorMessage":""}. 
![image](https://user-images.githubusercontent.com/107904131/213335141-6519e973-f371-4f0d-bac4-347cb807307f.png)

**Comment by liulongbin1314** [comment]
已修复，更新插件到 v1.1.1 后即可正常使用

**Comment by longan2244** [comment]
> 已修复，更新插件到 v1.1.1 后即可正常使用

收到
